package resources.jbpm.rules

import org.nh.pharmacy.domain.StockIndent;
import org.nh.pharmacy.domain.enumeration.Status;
import org.nh.jbpm.domain.dto.Error;
import org.nh.common.dto.UserDTO;


/*rule "stock_indent_document_creator_can_not_be_approver"
agenda-group "stock_indent_document_approver_validation"
    when
    $error : Error()
    $fact  : StockIndent(document.createdBy == null || (document.approvedBy != null && ((document.createdBy.login).equals(document.approvedBy.login))))
    then
    $error.addError("10176" );
end*/


rule "status_should_be_waiting_for_approval"
agenda-group "stock_indent_rules"
    when
     $error : Error()
     $fact  : StockIndent(document.status != Status.WAITING_FOR_APPROVAL)
    then
     $error.addError("10020" );
end


rule "status_should_be_draft_for_delete"
agenda-group "delete_validation"
when
     $error : Error()
     $fact  : StockIndent(document.status != Status.DRAFT)
    then
     $error.addError("10021" );
end

rule "status_should_be_draft_or_null"
agenda-group "send_for_approval_validation"
    when
        $error : Error()
        $fact  : StockIndent(document.status != Status.DRAFT, document.status != null)
    then
        $error.addError("10022" );
end
